name = "gracegate-site"
main = "worker.js"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "public"

[[kv_namespaces]]
binding = "WAITLIST"
id = "cecc77215a484b93a09c25c62bb476a0"
